/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author leoar
 */
public class frmCadastrarOperador extends javax.swing.JFrame {

    /**
     * Creates new form frmCadastrarOperador
     */
    
    
    
    public frmCadastrarOperador(Manufatura manft) {
        initComponents();
        this.mnft = manft;
    }
    
        Manufatura mnft;
        
        public static void infoBox(String infoMessage, String titleBar){
        JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
        
    public Data calculaIdadePessoa(String data){
        Pessoa p = new Pessoa();
        Data d = new Data();
        d.setDia(Integer.parseInt(data.substring(0,2)));
        d.setMes(Integer.parseInt(data.substring(3,5)));
        d.setAno(Integer.parseInt(data.substring(6,10)));
        p.setDataNasc(d);
        txtIdadeOperador.setText(p.calculaIdade());
        return d;
    }
    public Data montaDataNascOperador(String data){
        Data d = new Data();
        d.setDia(Integer.parseInt(data.substring(0,2)));
        d.setMes(Integer.parseInt(data.substring(3,5)));
        d.setAno(Integer.parseInt(data.substring(6,10)));
        return d;
    }
    public Endereco montaEnderecoOperador(){
        Endereco end = new Endereco();
        end.setRua(txtRuaOperador.getText());
        end.setBairro(txtBairroOperador.getText());
        end.setNumero(Integer.parseInt(txtNumeroOperador.getText()));
        end.setCidade(txtCidadeOperador.getText());
        end.setEstado(txtEstadoOperador.getText());
        return end;
    }
    public Operador formataOperador(){
        Operador op = new Operador();
        op.setNome(txtNomeOperador.getText());
        op.setIdade(txtIdadeOperador.getText());
        op.setCpf(txtCpfOperador.getText());
        op.setDataNasc(montaDataNascOperador(txtDtNascOperador.getText()));
        op.setSalarioHora(Float.parseFloat(txtSalarioOperador.getText()));
        op.setEndereço(montaEnderecoOperador());
        op.setCargo(txtCargoOperador.getText());
        return op;
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnCadastrarOperador = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtEstadoOperador = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBairroOperador = new javax.swing.JTextField();
        txtNumeroOperador = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCidadeOperador = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRuaOperador = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNomeOperador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDtNascOperador = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIdadeOperador = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCpfOperador = new javax.swing.JFormattedTextField();
        txtCargoOperador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSalarioOperador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Operador");
        getContentPane().setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        btnCadastrarOperador.setText("Cadastrar");
        btnCadastrarOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarOperadorActionPerformed(evt);
            }
        });
        jPanel3.add(btnCadastrarOperador);
        btnCadastrarOperador.setBounds(190, 350, 90, 32);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Endereço"));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(null);
        jPanel2.add(txtEstadoOperador);
        txtEstadoOperador.setBounds(77, 18, 90, 25);

        jLabel8.setText("Estado:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(11, 22, 60, 16);

        jLabel9.setText("Bairro:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(11, 52, 60, 16);
        jPanel2.add(txtBairroOperador);
        txtBairroOperador.setBounds(77, 48, 90, 25);
        jPanel2.add(txtNumeroOperador);
        txtNumeroOperador.setBounds(77, 78, 90, 25);

        jLabel10.setText("Número:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(11, 82, 60, 16);

        jLabel11.setText("Cidade:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(185, 22, 60, 16);
        jPanel2.add(txtCidadeOperador);
        txtCidadeOperador.setBounds(251, 18, 158, 25);

        jLabel12.setText("Rua:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(185, 52, 60, 16);
        jPanel2.add(txtRuaOperador);
        txtRuaOperador.setBounds(251, 48, 158, 25);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(30, 230, 420, 120);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Dados Pessoais"));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jLabel4.setText("Nome:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 30, 60, 16);
        jPanel1.add(txtNomeOperador);
        txtNomeOperador.setBounds(80, 30, 332, 25);

        jLabel5.setText("Data de nasc.:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 70, 100, 16);

        try {
            txtDtNascOperador.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDtNascOperador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDtNascOperador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDtNascOperadorFocusLost(evt);
            }
        });
        jPanel1.add(txtDtNascOperador);
        txtDtNascOperador.setBounds(120, 70, 80, 25);

        jLabel6.setText("Idade:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(270, 70, 34, 16);

        txtIdadeOperador.setEditable(false);
        jPanel1.add(txtIdadeOperador);
        txtIdadeOperador.setBounds(310, 70, 101, 25);

        jLabel7.setText("CPF:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 110, 100, 20);

        try {
            txtCpfOperador.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfOperador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCpfOperador);
        txtCpfOperador.setBounds(120, 110, 105, 25);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(30, 90, 420, 140);
        jPanel3.add(txtCargoOperador);
        txtCargoOperador.setBounds(70, 40, 90, 24);

        jLabel3.setText("Cargo:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 30, 50, 40);

        jLabel2.setText("Salário por hora:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(230, 30, 100, 40);
        jPanel3.add(txtSalarioOperador);
        txtSalarioOperador.setBounds(330, 40, 130, 24);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 476, 416);

        setSize(new java.awt.Dimension(476, 416));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDtNascOperadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDtNascOperadorFocusLost

        calculaIdadePessoa(txtDtNascOperador.getText());
    }//GEN-LAST:event_txtDtNascOperadorFocusLost

    private void btnCadastrarOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarOperadorActionPerformed
        if (!"".equals(txtCargoOperador.getText()) && !"".equals(txtSalarioOperador.getText()) && !"".equals(txtBairroOperador.getText()) && !"".equals(txtCidadeOperador.getText()) && !"".equals(txtCpfOperador.getText()) && !"".equals(txtEstadoOperador.getText()) && !"".equals(txtDtNascOperador.getText()) && !"".equals(txtIdadeOperador.getText()) && !"".equals(txtNomeOperador.getText()) && !"".equals(txtNumeroOperador.getText()) & !"".equals(txtRuaOperador.getText())){
        mnft.getProcesso().setOperador(formataOperador()); 
        this.dispose();
        }else{
            this.setAlwaysOnTop(false);
            infoBox("Há campos em branco, preencha-os!", "Campos em branco");
        }
    }//GEN-LAST:event_btnCadastrarOperadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //txtCargoOperador       /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCadastrarOperador(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarOperador;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtBairroOperador;
    private javax.swing.JTextField txtCargoOperador;
    private javax.swing.JTextField txtCidadeOperador;
    private javax.swing.JFormattedTextField txtCpfOperador;
    private javax.swing.JFormattedTextField txtDtNascOperador;
    private javax.swing.JTextField txtEstadoOperador;
    private javax.swing.JTextField txtIdadeOperador;
    private javax.swing.JTextField txtNomeOperador;
    private javax.swing.JTextField txtNumeroOperador;
    private javax.swing.JTextField txtRuaOperador;
    private javax.swing.JTextField txtSalarioOperador;
    // End of variables declaration//GEN-END:variables
}
