/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import static Classes.frmCadastrarEquipamento.infoBox;
import javax.swing.JOptionPane;

/**
 *
 * @author leoar
 */
public class frmCadastrarProduto extends javax.swing.JFrame {

    /**
     * Creates new form frmCadastrarProduto
     */
    public frmCadastrarProduto(Pedido ped, frmCadastrarPedido pedi) {
        initComponents();
        pd = ped;
        frmped = pedi;
    }
    frmCadastrarPedido frmped;
    Pedido pd;
    Manufatura mnft = new Manufatura();
    Ingrediente ingr = new Ingrediente();
    
    public static void infoBox(String infoMessage, String titleBar){
        JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCustoProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCadastrarProduto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtProcessoManufatura = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCustoHoraManufatura = new javax.swing.JTextField();
        btnCadastrarManufatura = new javax.swing.JButton();
        btnEquipamento = new javax.swing.JButton();
        btnOperador = new javax.swing.JButton();
        txtQtdeHoras = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtNomeIngrediente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUnidadeIngrediente = new javax.swing.JTextField();
        txtPrecoIngrediente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtQtdeIngrediente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFornecedorIngrediente = new javax.swing.JTextField();
        btnCadastrarIngrediente = new javax.swing.JButton();
        btnVoltarProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Produto");
        getContentPane().setLayout(null);
        getContentPane().add(txtNomeProduto);
        txtNomeProduto.setBounds(60, 20, 90, 24);

        jLabel2.setText("Custo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 10, 50, 40);

        txtCustoProduto.setEditable(false);
        getContentPane().add(txtCustoProduto);
        txtCustoProduto.setBounds(320, 20, 130, 24);

        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 10, 50, 40);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        btnCadastrarProduto.setText("Cadastrar");
        btnCadastrarProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCadastrarProdutoFocusLost(evt);
            }
        });
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });
        jPanel3.add(btnCadastrarProduto);
        btnCadastrarProduto.setBounds(140, 360, 90, 32);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Manufatura"));
        jPanel2.setLayout(null);
        jPanel2.add(txtProcessoManufatura);
        txtProcessoManufatura.setBounds(75, 18, 102, 24);

        jLabel10.setText("Processo:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(11, 22, 58, 16);

        jLabel11.setText("Qtde horas:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(220, 20, 66, 20);

        txtCustoHoraManufatura.setEditable(false);
        jPanel2.add(txtCustoHoraManufatura);
        txtCustoHoraManufatura.setBounds(320, 50, 85, 24);

        btnCadastrarManufatura.setText("Cadastrar");
        btnCadastrarManufatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarManufaturaActionPerformed(evt);
            }
        });
        jPanel2.add(btnCadastrarManufatura);
        btnCadastrarManufatura.setBounds(310, 80, 87, 32);

        btnEquipamento.setText("Equipamento");
        btnEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipamentoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEquipamento);
        btnEquipamento.setBounds(160, 80, 104, 32);

        btnOperador.setText("Operador");
        btnOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperadorActionPerformed(evt);
            }
        });
        jPanel2.add(btnOperador);
        btnOperador.setBounds(10, 80, 84, 32);
        jPanel2.add(txtQtdeHoras);
        txtQtdeHoras.setBounds(320, 20, 85, 24);

        jLabel12.setText("Custo por hora:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(220, 50, 87, 20);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(30, 220, 420, 120);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Ingrediente"));
        jPanel1.setLayout(null);
        jPanel1.add(txtNomeIngrediente);
        txtNomeIngrediente.setBounds(77, 24, 332, 24);

        jLabel4.setText("Nome:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(11, 28, 60, 16);

        jLabel6.setText("Unidade:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(11, 58, 60, 16);
        jPanel1.add(txtUnidadeIngrediente);
        txtUnidadeIngrediente.setBounds(77, 54, 112, 24);
        jPanel1.add(txtPrecoIngrediente);
        txtPrecoIngrediente.setBounds(77, 84, 112, 24);

        jLabel7.setText("Preço:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(11, 88, 37, 16);
        jPanel1.add(txtQtdeIngrediente);
        txtQtdeIngrediente.setBounds(297, 84, 112, 24);

        jLabel8.setText("Fornecedor:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(220, 60, 80, 16);

        jLabel9.setText("Quantidade:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(223, 88, 80, 16);
        jPanel1.add(txtFornecedorIngrediente);
        txtFornecedorIngrediente.setBounds(297, 54, 112, 24);

        btnCadastrarIngrediente.setText("Cadastrar");
        btnCadastrarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarIngredienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrarIngrediente);
        btnCadastrarIngrediente.setBounds(167, 117, 87, 32);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(30, 60, 420, 160);

        btnVoltarProduto.setText("Voltar");
        btnVoltarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarProdutoActionPerformed(evt);
            }
        });
        jPanel3.add(btnVoltarProduto);
        btnVoltarProduto.setBounds(270, 360, 64, 32);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 476, 416);

        setSize(new java.awt.Dimension(476, 416));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipamentoActionPerformed
        this.setAlwaysOnTop(false);
        frmCadastrarEquipamento frmeqp = new frmCadastrarEquipamento(mnft);
        frmeqp.setUndecorated(true);
        frmeqp.setVisible(true);
        
        //não deixa cadastrar novamente até que a manufatura seja cadastrada
        btnEquipamento.setEnabled(false);
    }//GEN-LAST:event_btnEquipamentoActionPerformed

    private void btnOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperadorActionPerformed
        this.setAlwaysOnTop(false);
        frmCadastrarOperador frmco = new frmCadastrarOperador(mnft);
        frmco.setUndecorated(true);
        frmco.setVisible(true);

        btnOperador.setEnabled(false);
    }//GEN-LAST:event_btnOperadorActionPerformed

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        if(p.getManufatura().size() > 0){
            if(p.getIngredientes().size() > 0){
                if(!"".equals(txtNomeProduto.getText())){
                    p.setNome(txtNomeProduto.getText());
                    p.setCusto(Float.parseFloat(txtCustoProduto.getText()));
                    pd.getProdutos().add(p);
                    pd.setTotalPedido(pd.calculaPedido());
                    frmped.calculaCusto();
                    this.dispose();
                }else{
                    infoBox("Nome do produto vazio!", "Campos em branco");
                }
            }else{
                infoBox("Ingredientes não cadastrados!", "Campos em branco");
            }
        }else{
            infoBox("Manufatura não cadastrada!", "Campos em branco");
        }
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed
    Produto p = new Produto();
    private void btnCadastrarManufaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarManufaturaActionPerformed
        if (!"".equals(txtProcessoManufatura.getText()) && !"".equals(txtQtdeHoras.getText())){
            if(mnft.getProcesso().getOperador() != null){
                if(mnft.getProcesso().getEquipamento() != null){
        mnft.getProcesso().setNome(txtProcessoManufatura.getText());
        p.getManufatura().add(mnft);
        txtCustoHoraManufatura.setText(String.valueOf(mnft.getProcesso().calculaCusto()));
        mnft.setQtde(Float.parseFloat(txtQtdeHoras.getText()));
        btnOperador.setEnabled(true);
        btnEquipamento.setEnabled(true);
        mnft = new Manufatura();
        txtCustoProduto.setText(String.valueOf(p.calculaCusto()));
                }else{
                    infoBox("Equipamento vazio!", "Campos em branco");
                }
            }else{
                infoBox("Operador vazio!", "Campos em branco");
            }
        }else{
            infoBox("Há campos em branco, preencha-os!", "Campos em branco");
        }
    }//GEN-LAST:event_btnCadastrarManufaturaActionPerformed
    public MateriaPrima formataMateria(){
       MateriaPrima pr = new MateriaPrima();
       pr.setNome(txtNomeIngrediente.getText());
       pr.setFornecedor(txtFornecedorIngrediente.getText());
       pr.setPreco(Float.parseFloat(txtPrecoIngrediente.getText()));
       pr.setUnidade(txtUnidadeIngrediente.getText());
       return pr;
    }
    private void btnCadastrarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarIngredienteActionPerformed
       if (!"".equals(txtNomeIngrediente.getText()) && !"".equals(txtFornecedorIngrediente.getText()) && !"".equals(txtPrecoIngrediente.getText()) && !"".equals(txtUnidadeIngrediente.getText()) && !"".equals(txtQtdeIngrediente.getText())){
       ingr.setMateriaPrima(formataMateria());
       ingr.setQtde(Float.parseFloat(txtQtdeIngrediente.getText()));
       p.getIngredientes().add(ingr);
       ingr = new Ingrediente();
       txtCustoProduto.setText(String.valueOf(p.calculaCusto()));
       }else{
           infoBox("Há campos em branco, preencha-os!", "Campos em branco");
       }
    }//GEN-LAST:event_btnCadastrarIngredienteActionPerformed

    private void btnVoltarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarProdutoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarProdutoActionPerformed

    private void btnCadastrarProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarProdutoFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCadastrarProduto(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarIngrediente;
    private javax.swing.JButton btnCadastrarManufatura;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnEquipamento;
    private javax.swing.JButton btnOperador;
    private javax.swing.JButton btnVoltarProduto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCustoHoraManufatura;
    private javax.swing.JTextField txtCustoProduto;
    private javax.swing.JTextField txtFornecedorIngrediente;
    private javax.swing.JTextField txtNomeIngrediente;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPrecoIngrediente;
    private javax.swing.JTextField txtProcessoManufatura;
    private javax.swing.JTextField txtQtdeHoras;
    private javax.swing.JTextField txtQtdeIngrediente;
    private javax.swing.JTextField txtUnidadeIngrediente;
    // End of variables declaration//GEN-END:variables
}
